version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/php.ini
      - ./docker/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "8001:80"
      - "8000:8000"

    networks:
      - laravel
  
  db:
    platform: "linux/amd64"
    image: mysql:5.7
    # env_file:
    #   - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "db_name"
      MYSQL_USER: "db_user"
      MYSQL_PASSWORD: "db_password"
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
networks:
  laravel:
volumes:
  dbdata: